import { type ReactNode, useEffect } from "react";
import { Calendar, Moon, Sun, X, type LucideIcon } from "lucide-react";
import "./ui.css";

export type DateRange = "All Time" | "This Month" | "This Year" | "Past 3 Months" | "Past 6 Months";
export const DATE_RANGE_OPTIONS: DateRange[] = ["All Time", "This Month", "This Year", "Past 3 Months", "Past 6 Months"];
export const STATUS_COLORS: Record<string, string> = { "Data Added": "var(--accent)", "Not Started": "var(--accent)", Contacted: "var(--primary-accent)", "In Progress": "var(--primary-accent)", "Follow-up Sent": "#C98A2E", Unpaid: "#C98A2E", "Sample Provided": "#3E6FB5", "Closed - Won": "#2E8B57", Paid: "#2E8B57", "Closed - Lost": "#B0413E", "Pending Approval": "#8B6FB5", Delivered: "#3E9B6F" };
export const OPP_STAGES = [{ number: 1, label: "First Call", name: "First Call Made", color: "#3E6FB5" }, { number: 2, label: "Connected", name: "Call Connected", color: "#8B6FB5" }, { number: 3, label: "POC Email", name: "POC Email Captured", color: "#C98A2E" }, { number: 4, label: "Free Trial", name: "Free Trial", color: "#D9822B" }, { number: 5, label: "Paid & Won", name: "Paid & Won", color: "#2E8B57" }] as const;
function statusStyle(text: string) { const color = STATUS_COLORS[text] ?? "var(--accent)"; return { "--badge-color": color } as React.CSSProperties; }
export function ThemeToggle({ theme, onToggle }: { theme: "light" | "dark"; onToggle: () => void }) { return <button className="icon-button" aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} theme`} onClick={onToggle}>{theme === "dark" ? <Sun size={17} /> : <Moon size={17} />}</button>; }
export function Badge({ text }: { text: string }) { return <span className="badge" style={statusStyle(text)}>{text}</span>; }
export function DesignerStatusBadge({ status }: { status: string }) { return <span className="badge" style={statusStyle(status)}>{status === "Delivered" ? "Submitted" : status}</span>; }
export function StatCard({ icon: Icon, label, value, sub, delay = 0 }: { icon: LucideIcon; label: string; value: ReactNode; sub?: ReactNode; delay?: number }) { return <section className="stat-card fade-up" style={{ animationDelay: `${delay}ms` }}><div className="stat-card__top"><span className="icon-chip"><Icon size={17} /></span>{sub && <span className="stat-card__sub">{sub}</span>}</div><strong className="display mono-num">{value}</strong><span>{label}</span></section>; }
export function NavItem({ icon: Icon, label, active = false, onClick, badge }: { icon: LucideIcon; label: string; active?: boolean; onClick?: () => void; badge?: ReactNode }) { return <button className={`nav-item ${active ? "nav-item--active" : ""}`} onClick={onClick}><Icon size={18} /><span>{label}</span>{badge !== undefined && <span className="nav-item__badge">{badge}</span>}</button>; }
export function Tabs({ tabs, active, onChange }: { tabs: string[]; active: string; onChange: (tab: string) => void }) { return <div className="tabs" role="tablist">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={active === tab} className={active === tab ? "tabs__tab tabs__tab--active" : "tabs__tab"} onClick={() => onChange(tab)}>{tab}</button>)}</div>; }
export function SectionCard({ title, right, children }: { title: string; right?: ReactNode; children: ReactNode }) { return <section className="section-card fade-up"><header><h3 className="display">{title}</h3>{right}</header>{children}</section>; }
export function Modal({ title, onClose, children, width = 440 }: { title: string; onClose: () => void; children: ReactNode; width?: number }) { useEffect(() => { const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); addEventListener("keydown", close); return () => removeEventListener("keydown", close); }, [onClose]); return <div className="overlay fade-in" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" style={{ width }} onMouseDown={(event) => event.stopPropagation()}><header><h3 className="display">{title}</h3><button className="icon-button" aria-label="Close" onClick={onClose}><X size={18} /></button></header>{children}</section></div>; }
export function TextField({ label, value, onChange, placeholder, autoComplete = "off" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; autoComplete?: string }) { return <label className="field"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} autoComplete={autoComplete} /></label>; }
export function TextAreaField({ label, value, onChange, placeholder, rows = 3 }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; rows?: number }) { return <label className="field"><span>{label}</span><textarea value={value} rows={rows} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
export function DateRangeFilter({ value, onChange, label = "Date Range" }: { value: DateRange; onChange: (value: DateRange) => void; label?: string }) { return <label className="field field--compact"><span>{label}</span><div className="select-with-icon"><Calendar size={15} /><select value={value} onChange={(event) => onChange(event.target.value as DateRange)}>{DATE_RANGE_OPTIONS.map((option) => <option key={option}>{option}</option>)}</select></div></label>; }
export function Field({ icon: Icon, label, value, muted = false }: { icon: LucideIcon; label: string; value: ReactNode; muted?: boolean }) { return <div className="read-field"><Icon size={16} /><div><span>{label}</span><strong className={muted ? "muted" : ""}>{value}</strong></div></div>; }
export function Empty({ text }: { text: string }) { return <p className="empty-state">{text}</p>; }
export function MiniStat({ label, value, tone = "default" }: { label: string; value: ReactNode; tone?: "default" | "positive" | "warning" }) { return <div className={`mini-stat mini-stat--${tone}`}><span>{label}</span><strong className="display">{value}</strong></div>; }
export function TimelineRow({ text }: { text: string }) { return <div className="timeline-row"><i />{text}</div>; }
export function ProgressBar({ pct, tone = "var(--primary)" }: { pct: number; tone?: string }) { return <div className="progress"><span style={{ width: `${Math.min(Math.max(pct, 0), 100)}%`, background: tone }} /></div>; }
export function OpportunityStageBar({ stage }: { stage: number }) { return <div className="stage-bar">{OPP_STAGES.map((item, index) => <div className="stage" key={item.number}><div className="stage__line" style={{ background: index < stage - 1 ? OPP_STAGES[index].color : undefined }} /><span className={item.number <= stage ? "stage__dot stage__dot--reached" : "stage__dot"} style={item.number <= stage ? { background: item.color, borderColor: item.color } : undefined}>{item.number}</span><small>{item.label}</small></div>)}</div>; }
