import type { Assignment, Client, Designer, Expense, Lead, User } from "../domain/entities.js";
import type { Repositories } from "../services/crm.js";
import { InMemoryAssignmentRepository, InMemoryClientRepository, InMemoryDesignerRepository, InMemoryExpenseRepository, InMemoryLeadRepository, InMemoryNotificationRepository, InMemoryPushSubscriptionRepository, InMemorySessionRepository, InMemoryUserRepository } from "./in-memory.js";

const users: User[] = [{ id: "usr-admin", name: "Ayesha Khan", email: "ayesha@stitchcrm.com", role: "Admin" }, { id: "usr-caller-1", name: "Ahmed Farooqi", email: "ahmed@stitchcrm.com", role: "Caller" }];
const designers: Designer[] = [{ id: "des-1", name: "Mariam Shah", email: "mariam@stitchcrm.com" }, { id: "des-2", name: "Omar Ahmed", email: "omar@stitchcrm.com" }, { id: "des-3", name: "Zain Raza", email: "zain@stitchcrm.com" }, { id: "des-4", name: "Noor Fatima", email: "noor@stitchcrm.com" }];
const clients: Client[] = [
  { id: "cli-1", company: "Northstar Apparel", contact: "Elena Brooks", email: "elena@northstar.test", phone: "+1 212 555 0192", type: "Unpaid", createdAt: "2026-08-04", projects: [{ id: "prj-1", name: "Summer Cap Run", service: "Digitizing", designer: "Mariam Shah", status: "In Progress", startDate: "2026-08-05" }, { id: "prj-2", name: "Vector Logo Cleanup", service: "Vector Art", designer: "Omar Ahmed", status: "Delivered", startDate: "2026-07-21" }], billingMonth: "August 2026", totalAmount: 1250, paid: 750, payments: [{ date: "2026-07-25", amount: 300 }, { date: "2026-08-07", amount: 450 }], due: "USD 500", convertedFrom: null, convertedOn: null },
  { id: "cli-2", company: "Harbor Merch Co.", contact: "Marcus Lee", email: "marcus@harbormerch.test", phone: "+1 415 555 0177", type: "Paid", createdAt: "2026-06-14", projects: [{ id: "prj-3", name: "Patch Collection", service: "Custom Patches", designer: "Zain Raza", status: "Not Started", startDate: "2026-06-18" }], billingMonth: "June 2026", totalAmount: 900, paid: 900, payments: [{ date: "2026-06-19", amount: 900 }], due: "USD 0", convertedFrom: null, convertedOn: null }
];
const assignments: Assignment[] = [{ id: "asn-1", designerName: "Mariam Shah", designerEmail: "mariam@stitchcrm.com", clientCompany: "Northstar Apparel", projectName: "Summer Cap Run", logoName: "Northstar Crest", projectType: "Digitizing", description: "3D puff cap artwork", assignedDate: "2026-08-05", payment: 12000, paid: 0, attachmentName: "crest.pdf", attachedFiles: ["crest.pdf"], emailSent: true }, { id: "asn-2", designerName: "Omar Ahmed", designerEmail: "omar@stitchcrm.com", clientCompany: "Northstar Apparel", projectName: "Vector Logo Cleanup", logoName: "Northstar Wordmark", projectType: "Vector Art", description: "Clean vector for embroidery", assignedDate: "2026-07-21", payment: 8500, paid: 8500, attachmentName: null, attachedFiles: [], emailSent: true }, { id: "asn-3", designerName: "Zain Raza", designerEmail: "zain@stitchcrm.com", clientCompany: "Harbor Merch Co.", projectName: "Patch Collection", logoName: "Harbor Anchor", projectType: "Custom Patches", description: "Merrowed patch collection", assignedDate: "2026-06-18", payment: 15000, paid: 6000, attachmentName: "anchor.ai", attachedFiles: ["anchor.ai", "notes.txt"], emailSent: true }, { id: "asn-4", designerName: "Mariam Shah", designerEmail: "mariam@stitchcrm.com", clientCompany: "—", projectName: "Manual payment", logoName: "—", projectType: "—", description: "Advance against future work", assignedDate: "2026-08-09", payment: 5000, paid: 0, attachmentName: null, attachedFiles: [], emailSent: false }];
const leads: Lead[] = [
  { id: "lead-1", company: "Atlas Uniforms", phone: "+1 (206) 555-0188", website: "atlas.test", social: "", contactName: "Jordan Kim", contactRole: "Buyer", email: "", status: "Data Added", hot: false, owner: "Hamza", capturedBy: "Ayesha", assignedBy: "Ayesha Khan", assignedAt: "2026-08-10T10:00:00Z", isNew: true, createdAt: "2026-08-10", country: "USA", city: "Seattle", opportunity: null, calls: [], followups: [] },
  { id: "lead-2", company: "Pine & Thread", phone: "+1 303 555 0120", website: "", social: "linkedin.com/pine", contactName: "Priya Singh", contactRole: "Owner", email: "priya@pine.test", status: "Contacted", hot: true, owner: "Sara", capturedBy: "Sara", assignedBy: "Ayesha Khan", assignedAt: "2026-08-02T10:00:00Z", isNew: false, createdAt: "2026-08-01", country: "USA", city: "Denver", opportunity: { connected: true, createdAt: "2026-08-03", pocs: [{ id: "poc-1", name: "Priya Singh", role: "Owner", email: "priya@pine.test", phone: "+1 303 555 0120" }], trial: { given: false, date: "", logoName: "", projectType: "", notes: "" }, orders: [] }, calls: [{ date: "Aug 3, 2026", duration: "2m 10s", durationSeconds: 130, notes: "Interested in samples", timestamp: 1785761400000 }], followups: [{ date: "Aug 17, 2026", time: "14:00", notes: "Send vector sample" }] },
  { id: "lead-3", company: "Cedar Goods", phone: "+1 512 555 0145", website: "cedar.test", social: "", contactName: "Luis Torres", contactRole: "Marketing", email: "luis@cedar.test", status: "Sample Provided", hot: true, owner: "Hamza", capturedBy: "Hamza", assignedBy: "Ayesha Khan", assignedAt: "2026-07-12T10:00:00Z", isNew: false, createdAt: "2026-07-10", country: "USA", city: "Austin", opportunity: { connected: true, createdAt: "2026-07-11", pocs: [{ id: "poc-2", name: "Luis Torres", role: "Marketing", email: "luis@cedar.test", phone: "" }], trial: { given: true, date: "2026-07-14", logoName: "Cedar Badge", projectType: "Custom Patches", notes: "Awaiting approval" }, orders: [] }, calls: [{ date: "Jul 11, 2026", duration: "48s", durationSeconds: 48, notes: "Discussed trial", timestamp: 1783766400000 }], followups: [] },
  { id: "lead-4", company: "Riverline Sports", phone: "+1 312 555 0103", website: "", social: "", contactName: "", contactRole: "", email: "", status: "Pending Approval", hot: false, owner: "Sara", capturedBy: "Sara", assignedBy: "", assignedAt: "2026-08-15T10:00:00Z", isNew: true, createdAt: "2026-08-15", country: "USA", city: "Chicago", opportunity: null, calls: [], followups: [] }
  ,{ id: "lead-5", company: "Summit Outfitters", phone: "+1 720 555 0161", website: "", social: "", contactName: "Jamie Park", contactRole: "Operations", email: "", status: "Follow-up Sent", hot: false, owner: "Hamza", capturedBy: "Ayesha", assignedBy: "Ayesha Khan", assignedAt: "2026-06-08T10:00:00Z", isNew: false, createdAt: "2026-06-07", country: "USA", city: "Boulder", opportunity: null, calls: [], followups: [{ date: "Aug 17, 2026", time: "11:00", notes: "Confirm pricing" }] }
  ,{ id: "lead-6", company: "Golden State Tees", phone: "+1 510 555 0130", website: "goldenstate.test", social: "", contactName: "Riley Chen", contactRole: "Founder", email: "riley@goldenstate.test", status: "Closed - Won", hot: true, owner: "Sara", capturedBy: "Sara", assignedBy: "Ayesha Khan", assignedAt: "2026-05-11T10:00:00Z", isNew: false, createdAt: "2026-05-09", country: "USA", city: "Oakland", opportunity: { connected: true, createdAt: "2026-05-10", pocs: [{ id: "poc-3", name: "Riley Chen", role: "Founder", email: "riley@goldenstate.test", phone: "" }], trial: { given: true, date: "2026-05-12", logoName: "Golden State Script", projectType: "Digitizing", notes: "Approved" }, orders: [{ projectName: "Varsity Jacket Set", amount: 1400, notes: "Initial production order", date: "2026-05-16" }] }, calls: [{ date: "May 10, 2026", duration: "1m 3s", durationSeconds: 63, notes: "Qualified lead", timestamp: 1778371200000 }], followups: [] }
  ,{ id: "lead-7", company: "Metro Clubwear", phone: "+1 646 555 0115", website: "", social: "", contactName: "Taylor Jones", contactRole: "Buyer", email: "", status: "Closed - Lost", hot: true, owner: "Hamza", capturedBy: "Hamza", assignedBy: "Ayesha Khan", assignedAt: "2026-03-05T10:00:00Z", isNew: false, createdAt: "2026-03-04", country: "USA", city: "New York", opportunity: { connected: false, createdAt: "2026-03-05", pocs: [], trial: { given: false, date: "", logoName: "", projectType: "", notes: "" }, orders: [] }, calls: [{ date: "Mar 5, 2026", duration: "18s", durationSeconds: 18, notes: "Not a fit", timestamp: 1772737200000 }], followups: [] }
  ,...[["Northline Apparel Co.", "Dana Wolfe", "Portland"], ["Ridgeback Embroidery Supply", "Marcus Reyes", "Dallas"], ["Sable & Thread Studio", "Nina Patel", "Miami"], ["Coastline DTF Prints", "Owen Brooks", "San Diego"], ["Heritage Workwear", "Morgan Lee", "Boston"], ["Evergreen Team Gear", "Alex Morgan", "Portland"], ["Canyon Stitchworks", "Casey Brown", "Phoenix"], ["Lakeside Apparel", "Chris Evans", "Minneapolis"], ["Oak & Ink Uniforms", "Taylor Reed", "Nashville"], ["Silverline Sportswear", "Sam Wilson", "Atlanta"], ["Blue Ridge Patches", "Avery Davis", "Richmond"], ["Frontier Logo Lab", "Robin Clark", "Denver"], ["Capital Teamwear", "Jamie Cole", "Washington"]].map(([company, contactName, city], index): Lead => ({ id: `lead-${index + 8}`, company, phone: `+1 555 010 ${String(index + 8).padStart(2, "0")}`, website: "", social: "", contactName, contactRole: "Owner", email: "", status: "Data Added", hot: false, owner: index % 2 ? "Sara" : "Hamza", capturedBy: "Ayesha", assignedBy: "Ayesha Khan", assignedAt: `2026-08-${String(Math.max(1, 20 - index)).padStart(2, "0")}T10:00:00Z`, isNew: false, createdAt: `2026-08-${String(Math.max(1, 19 - index)).padStart(2, "0")}`, country: "USA", city, opportunity: null, calls: [], followups: [] }))
  ,...Array.from({ length: 30 }, (_, index): Lead => ({ id: `lead-${index + 21}`, company: `Demo Embroidery Company ${index + 1}`, phone: `+1 555 020 ${String(index + 1).padStart(2, "0")}`, website: "", social: "", contactName: `Demo Contact ${index + 1}`, contactRole: "Manager", email: "", status: "Data Added", hot: false, owner: index % 2 ? "Hamza" : "Sara", capturedBy: "Ayesha", assignedBy: "Ayesha Khan", assignedAt: `2026-07-${String((index % 28) + 1).padStart(2, "0")}T09:00:00Z`, isNew: false, createdAt: `2026-07-${String((index % 28) + 1).padStart(2, "0")}`, country: "USA", city: ["Houston", "Orlando", "Columbus", "Charlotte", "Detroit"][index % 5], opportunity: null, calls: [], followups: [] }))
];
const expenses: Expense[] = [{ id: "exp-1", name: "Studio internet", amount: 9000, date: "2026-08-01" }, { id: "exp-2", name: "Design software", amount: 14000, date: "2026-08-03" }, { id: "exp-3", name: "Contractor tools", amount: 6500, date: "2026-07-15" }, { id: "exp-4", name: "Office supplies", amount: 3200, date: "2026-07-03" }, { id: "exp-5", name: "Cloud hosting", amount: 4800, date: "2026-06-12" }, { id: "exp-6", name: "Phone credits", amount: 7100, date: "2026-05-27" }];
export function createSeededRepositories() { return { users: new InMemoryUserRepository(structuredClone(users)), designers: new InMemoryDesignerRepository(structuredClone(designers)), clients: new InMemoryClientRepository(structuredClone(clients)), assignments: new InMemoryAssignmentRepository(structuredClone(assignments)), leads: new InMemoryLeadRepository(structuredClone(leads)), expenses: new InMemoryExpenseRepository(structuredClone(expenses)), notifications: new InMemoryNotificationRepository([]), sessions: new InMemorySessionRepository([]), pushSubscriptions: new InMemoryPushSubscriptionRepository([]) }; }

/** Adds the existing demo data only to an empty persistent CRM database. */
export async function seedPersistentRepositories(repositories: Repositories) {
  if ((await repositories.users.findAll()).length) return false;
  const source = createSeededRepositories();
  for (const user of await source.users.findAll()) await repositories.users.create(user);
  for (const designer of await source.designers.findAll()) await repositories.designers.create(designer);
  for (const lead of await source.leads.findAll()) await repositories.leads.create(lead);
  for (const client of await source.clients.findAll()) await repositories.clients.create(client);
  for (const assignment of await source.assignments.findAll()) await repositories.assignments.create(assignment);
  for (const expense of await source.expenses.findAll()) await repositories.expenses.create(expense);
  return true;
}
